From c8d9ff0f0dd808fbdd709e547aa38d81ffd44bf0 Mon Sep 17 00:00:00 2001
From: Ronan Abhamon <ronan.abhamon@vates.fr>
Date: Fri, 15 Jan 2021 17:01:05 +0100
Subject: [PATCH 031/171] fix(LinstorSR): call correctly method in _locked_load
 when vdi_attach_from_config is executed

Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>
---
 drivers/LinstorSR.py | 19 ++++++-------------
 1 file changed, 6 insertions(+), 13 deletions(-)

diff --git a/drivers/LinstorSR.py b/drivers/LinstorSR.py
index 16cb0d6..2df2d68 100755
--- a/drivers/LinstorSR.py
+++ b/drivers/LinstorSR.py
@@ -347,19 +347,12 @@ class LinstorSR(SR.SR):
                         self._master_uri, self._group_name, logger=util.SMlog
                     )
 
-                    try:
-                        self._linstor = LinstorVolumeManager(
-                            self._master_uri,
-                            self._group_name,
-                            logger=util.SMlog
-                        )
-                        return
-                    except Exception as e:
-                        util.SMlog(
-                            'Ignore exception. Failed to build LINSTOR '
-                            'instance without session: {}'.format(e)
-                        )
-                return
+                    self._linstor = LinstorVolumeManager(
+                        self._master_uri,
+                        self._group_name,
+                        logger=util.SMlog
+                    )
+                return method(self, *args, **kwargs)
 
             self._master_uri = 'linstor://{}'.format(
                 util.get_master_rec(self.session)['address']
-- 
2.44.0

