From 4a967082c1598cf71f6abc4952911c7e15b46ba8 Mon Sep 17 00:00:00 2001
From: Damien Thenot <damien.thenot@vates.tech>
Date: Fri, 27 Jun 2025 10:20:38 +0200
Subject: [PATCH] fix(cleanup.py): call correctly isCoalesceableOnRemote

Signed-off-by: Damien Thenot <damien.thenot@vates.tech>
---
 drivers/cleanup.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/drivers/cleanup.py b/drivers/cleanup.py
index 0cc5d283..eb92baa3 100755
--- a/drivers/cleanup.py
+++ b/drivers/cleanup.py
@@ -2503,7 +2503,7 @@ class SR(object):
                 raise Exception("Not coalesceable, chain activated more than once") #TODO: Use correct error
 
             try:
-                if host_refs and vdi.cowutil.isCoalesceableOnRemote:
+                if host_refs and vdi.cowutil.isCoalesceableOnRemote():
                     #Leaf opened on another host, we need to call online coalesce
                     util.SMlog("Remote coalesce for {}".format(vdi.path))
                     vdi._doCoalesceOnHost(list(host_refs)[0])
