From a600cd8fb9c29b709459b7446fc7fd0ac362bbdf Mon Sep 17 00:00:00 2001
From: Ronan Abhamon <ronan.abhamon@vates.fr>
Date: Tue, 14 Nov 2023 18:21:53 +0100
Subject: [PATCH 141/176] fix(linstorvhdutil): format correctly message if
 vhd-util cannot be run

Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>
---
 drivers/linstorvhdutil.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/drivers/linstorvhdutil.py b/drivers/linstorvhdutil.py
index 5f3ae08..3ce7ab9 100644
--- a/drivers/linstorvhdutil.py
+++ b/drivers/linstorvhdutil.py
@@ -441,7 +441,7 @@ class LinstorVhdUtil:
 
             raise xs_errors.XenError(
                 'VDIUnavailable',
-                opterr='No valid host found to run vhd-util command `{}` (path=`{}`, openers=`{}`): {}'
-                .format(remote_method, device_path, openers, e)
+                opterr='No valid host found to run vhd-util command `{}` (path=`{}`, openers=`{}`)'
+                .format(remote_method, device_path, openers)
             )
         return util.retry(remote_call, 5, 2)
-- 
2.45.2

