From 5d5ec1da0853a7dd00bfe4fb06ee8ac42f2f08cb Mon Sep 17 00:00:00 2001
From: Ronan Abhamon <ronan.abhamon@vates.fr>
Date: Tue, 6 Feb 2024 00:14:11 +0100
Subject: [PATCH 161/170] fix(LinstorSR): fix bad call to vhdutil.inflate + bad
 exception

Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>
---
 drivers/LinstorSR.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/drivers/LinstorSR.py b/drivers/LinstorSR.py
index 53afbef..de10f42 100755
--- a/drivers/LinstorSR.py
+++ b/drivers/LinstorSR.py
@@ -1944,7 +1944,7 @@ class LinstorVDI(VDI.VDI):
         else:
             if new_volume_size != old_volume_size:
                 self.sr._vhdutil.inflate(
-                    self.sr._journaler, self._linstor, self.uuid, self.path,
+                    self.sr._journaler, self.uuid, self.path,
                     new_volume_size, old_volume_size
                 )
             self.sr._vhdutil.set_size_virt_fast(self.path, size)
@@ -2497,7 +2497,7 @@ class LinstorVDI(VDI.VDI):
             self.session.xenapi.VDI.set_sm_config(
                 vdi_ref, active_vdi.sm_config
             )
-        except Exception as e:
+        except Exception:
             util.logException('Failed to snapshot!')
             try:
                 self.sr._handle_interrupted_clone(
-- 
2.44.0

